### ISSUE TITLE
abort python start.py

### ISSUE THREAD

**Issue by gabrielnm123** [ebankoff/Beast_Bomber#46]
Good night, how are you?
Out of nowhere at the start of execution **python aborts**

`$ python start.py`
`Requirement already satisfied: configparser in ./lib/python3.10/site-packages (5.3.0)`
`[1]    18020 abort      python start.py`

**Output result uname --all:**

`$ uname --all`
`Linux zorin 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Output result python --version:**

`$ python --version`
`Python 3.10.2`

**Comment by ebankoff** [comment]
Hello! Try reinstalling python and updating all the pip libraries, no other ideas

**Comment by GNEUGNEUGNEU** [comment]
Hi, i did reinstall everything and update but still when i do python3 start.py this is all i got : 

python3 start.py
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: configparser in /usr/local/lib/python3.10/dist-packages (5.3.0)
zsh: IOT instruction  python3 start.py

thx for your help

**Comment by up2smoke** [comment]
why u close every request and said "reinstall python" but it dont work. Are u a scammer @ebankoff
